project:
  type: website
  output-dir: _site

website:
  title: "R Progress Analysis"
  navbar:
    left:
      - text: "Analysis"
        file: drmMar18.qmd

format:
  html:
    theme: cosmo
    toc: true

